# Jekyll configuration

name: HeKo
description: Partiolippukunta Helsingin Kotkat

# url is currently only used only for the RSS feed in feed.xml
url: https://heko.org


# This can be '' to hide the Github nav button
github: 'helsinginkotkat/website'

# Set this to your UA-# value, or '' to disable the block completely

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: false 


paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
